		[types.wood_type.abundant_atmosphere]
			red_bamboo = true
			ashroot = true
			gourdrot = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.newworld]
			fir = true

		[types.wood_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.lantern.caverns_and_chasms]
			cupric_lantern = true
			copper_lantern = true
			exposed_copper_lantern = true
			weathered_copper_lantern = true
			oxidized_copper_lantern = true
			waxed_copper_lantern = true
			waxed_exposed_copper_lantern = true
			waxed_weathered_copper_lantern = true
			waxed_oxidized_copper_lantern = true

		[types.leaves_type.abundant_atmosphere]
			ashroot = true
			gourdrot = true

		[types.leaves_type.nomansland]
			autumnal_oak = true
			frosted = true
			pale_cherry = true
			red_maple = true
			yellow_birch = true
			pine = true
			maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[types.leaves_type.newworld]
			fir = true

		[types.leaves_type.cobblemon]
			apricorn = true
			saccharine = true

		[entries.wood_type.another_furniture]
			drawer = true
			table = true
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.nomansland]
			bookshelf = true
			trimmed_planks = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.envelope]
			pigeonhole = true
